# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=140)),
                ('Slot', models.CharField(max_length=140)),
            ],
        ),
    ]
