# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_post_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=140)),
            ],
        ),
    ]
